name: Invoicer deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/deployer/invoicer
            
            docker ps

            git pull origin master

            cd _docker 
            
            cp .env.example .env
            
            docker compose build
            
            docker compose up -d
            
            cd /home/deployer/invoicer/sources
            
            echo "APP_ENV=prod" >> .env
            
            echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
            
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            
            echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}" >> .env
            
            echo "MAILER_DSN=${{ secrets.MAILER_DSN }}" >> .env
            
            pwd 
            
            cat .env
            
            cd /home/deployer/invoicer/_docker
            
            docker compose exec php bash -c "cd sources && composer install"
            
            docker compose exec php bash -c "cd sources && pwd && ls && php bin/console doctrine:migrations:migrate"
            
            docker compose exec php bash -c "cd sources && supervisorctl restart messenger-consume:*"